# -*- coding: utf-8 -*-
"""Untitled28.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aRc7hlEAZhHNDuTy6dOFg9peGakQb_FG
"""

!pip install streamlit

primaryColor="#059435"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"